---
title: VentureSquad
<<<<<<< HEAD
timezone: UTC
=======
timezone: Europe/Amsterdam
>>>>>>> origin/gh-pages
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
<<<<<<< HEAD
    Position: ''
    Venture: ''
    linkedin:
    twitter:
permalink: date
author: VentureSquad
email: info@venturebuilders.nl
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description. '
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
=======
    layout: page
permalink: pretty
>>>>>>> origin/gh-pages
